### ISSUE TITLE
Documentation of the maven profiles

### ISSUE THREAD

**Issue by tatjana19** [lightblueseas/mvn-parent-projects#2]
Provide a documentation of the maven profiles with examples.

**Comment by astrapi69** [comment]
@tatjana19 in this parent project there is only one profile for for releasing artifacts (projects) on sonatype. The name of the profile is 'oss.sonatype.org-staged-release' and is self-explaining.

From the shell you can execute it with the following command:
```shell
:~$ mvn clean deploy -Poss.sonatype.org-staged-release
```
This is executed on this project or in a project that have this project as parent or parent of parent and so on.

If you use eclipse:

![eclipse_deploy_config](https://cloud.githubusercontent.com/assets/1822320/21930095/791ceb6e-d994-11e6-81da-706ea303d0c0.png)

On this screenshot you have the mvn-java-parent project that have this project as parent.


If you have a passphrase you have to insert it when a dialog pops up or you can give it as argument in the command.

From the shell you can execute it with the following command:
```shell
:~$ mvn clean deploy -Poss.sonatype.org-staged-release -Dgpg.passphrase=YOUR_PASSPHRASE
```
You can also set the gpg.passphrase in the file ~/.m2/settings.xml for not expose it. Before you write your gpg.passphrase in the settings.xml you can encrypt it, [here is a how to](http://blog.sonatype.com/2009/10/maven-tips-and-tricks-encrypting-passwords/).

and for eclipse:

![eclipse_deploy_config_with_passphrase](https://cloud.githubusercontent.com/assets/1822320/21930077/64555720-d994-11e6-8fb2-53715b80862f.png)



Before deploy on sonatype you should follow the instructions from sonatype.

 For instance if you have java project you should run javadoc for validate your javadocs.

From the shell you can execute it with the following command:
```shell
:~$ mvn javadoc:javadoc
```
 And for update your licence header you can use a specific profile. Here an exampe of it in this [issue](https://github.com/lightblueseas/mvn-java-parent/issues/8).

An example of it is in the mvn-java-parent. Last but not least the unit test of the project should not fail.
